version: "3"

services:
  # TODO:
  # ray-head가 만드는 docker container "ray_container" [--net=host]
  # 를 프록시할 수 있도록 할 것.
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "8000:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: "localhost"

  ray-head:
    image: ${RAY_IMAGE}
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: "localhost"
      VIRTUAL_PATH: /
      VIRTUAL_DEST: /
      VIRTUAL_PORT: "8001"

    command: sleep infinity

    shm_size: 4GB
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "4g"
    network_mode: "host"
    working_dir: "/mnt"
    volumes:
      - ./ray_test.py:/mnt/ray_test.py
      - ./cluster.yml:/mnt/cluster.yml
      - ./actor-cluster.yml:/mnt/actor-cluster.yml
      - ~/.ssh:/home/ray/.ssh:ro

  whoami:
    image: traefik/whoami
    environment:
      VIRTUAL_HOST: "localhost"
      VIRTUAL_PATH: /whoami
