version: "3"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "8000:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: "localhost"

  ray-head:
    image: ${RAY_IMAGE}
    ports:
      - "${REDISPORT}:${REDISPORT}"
      - "${DASHBOARDPORT}:${DASHBOARDPORT}"
      - "${HEADNODEPORT}:${HEADNODEPORT}"
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: "localhost"
      VIRTUAL_PATH: /
      VIRTUAL_DEST: /
      VIRTUAL_PORT: "8001"

    command:
      - python
      - /mnt/ray_test.py
    shm_size: 2g
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2g"
    volumes:
      - ./ray_test.py:/mnt/ray_test.py
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-O-",
          "--tries=1",
          "-q",
          "http://localhost:8001/healthcheck",
        ]
      interval: 1s
      start_interval: 1s

  ray-worker:
    image: ${RAY_IMAGE}
    depends_on:
      - ray-head
    env_file:
      - .env
    command: bash -c "ray start --address=ray-head:${REDISPORT} --block"
    shm_size: 2g
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: ${NUM_CPU_WORKER}
          memory: "2g"

  whoami:
    image: traefik/whoami
    environment:
      VIRTUAL_HOST: "localhost"
      VIRTUAL_PATH: /whoami
