version: "3"

services:
  ray-head:
    image: ${RAY_IMAGE}
    ports:
      - "${REDISPORT}:${REDISPORT}"
      - "${DASHBOARDPORT}:${DASHBOARDPORT}"
      - "${HEADNODEPORT}:${HEADNODEPORT}"
      - 8000:8000
    env_file:
      - .env
    command:
      - python
      - /mnt/ray_test.py
    shm_size: 2g
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2g"
    volumes:
      - ./ray_test.py:/mnt/ray_test.py

  ray-worker:
    image: ${RAY_IMAGE}
    depends_on:
      - ray-head
    env_file:
      - .env
    command: bash -c "ray start --address=ray-head:${REDISPORT} --block"
    shm_size: 2g
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: ${NUM_CPU_WORKER}
          memory: "2g"
